hk_mapping = {
    'ground': (0x4b14, 'Attack Ground'),
    'convert': (0x4b16, 'Convert'),
    'delete': (0x4a38, 'Delete Unit'),
    'build': (0x4b0e, 'Economic Buildings'),
    'garrison': (0x4a44, 'Garrison'),
    'heal': (0x4b15, 'Heal'),
    'mbuild': (0x4b0f, 'Military Buildings'),
    'pack': (0x4b29, 'Pack'),
    'repair': (0x4b18, 'Repair'),
    'setgather': (0x4a3a, 'Set Gather Point'),
    'stop': (0x4b10, 'Stop'),
    'unload': (0x4b19, 'Unload/Ungarrison'),
    'unpack': (0x4b2a, 'Unpack'),
    'chatmenu': (0x4b65, 'Chat Dialog'),
    'diplomacy': (0x4b62, 'Diplomacy'),
    'time': (0x4a42, 'Display Game Time'),
    'stats': (0x4b44, 'Display Statistics'),
    'tech': (0x4b52, 'Display Technology Tree'),
    'flare': (0x4b59, 'Flare'),
    'range': (0x4b46, 'Go to Archery Range'),
    'rax': (0x4b45, 'Go to Barracks'),
    'smith': (0x4b4b, 'Go to Blacksmith'),
    'castle': (0x4b5a, 'Go to Castle'),
    'dock': (0x4b49, 'Go to Dock'),
    'last': (0x4a50, 'Go to Last Notification'),
    'last2': (0x1004a50, 'Go to Last Notification (2)'),
    'lumber': (0x4b5c, 'Go to Lumber Camp'),
    'market': (0x4a53, 'Go to Market'),
    'mill': (0x4b4c, 'Go to Mill'),
    'mining': (0x4b5b, 'Go to Mining Camp'),
    'monastery': (0x4b4a, 'Go to Monastery'),
    'idlem': (0x4a7c, 'Go to Next Idle Military Unit'),
    'idlem2': (0x1004a7c, 'Go to Next Idle Military Unit (2)'),
    'idlev': (0x4a4f, 'Go to Next Idle Villager'),
    'idlev2': (0x1004a4f, 'Go to Next Idle Villager (2)'),
    'selected': (0x4a51, 'Go to Selected Object'),
    'siege': (0x4b48, 'Go to Siege Workshop'),
    'stable': (0x4b47, 'Go to Stable'),
    'tc': (0x4a52, 'Go to Town Center'),
    'tc2': (0x1004a52, 'Go to Town Center (2)'),
    'university': (0x4b4d, 'Go to University'),
    'cmap': (0x4b5d, 'Mini-map Combat Mode'),
    'emap': (0x4b5e, 'Mini-map Economic Mode'),
    'nmap': (0x4b5f, 'Mini-map Normal Mode'),
    'object': (0x4b64, 'Objectives'),
    'pause': (0x4b7b, 'Pause Game'),
    'chatback': (0x4a54, 'Review Chat Messages Backward'),
    'chatfor': (0x4a55, 'Review Chat Messages Forward'),
    'save': (0x4b7d, 'Save Game'),
    'chat': (0x4a39, 'Send Chat Message'),
    'slow': (0x4a3d, 'Slow Down Game'),
    'fast': (0x4a3c, 'Speed Up Game'),
    'down': (0x4a41, 'Scroll Down'),
    'left': (0x4a3e, 'Scroll Left'),
    'right': (0x4a3f, 'Scroll Right'),
    'up': (0x4a40, 'Scroll Up'),
    'brange': (0x4a76, 'Archery Range'),
    'brax': (0x4a78, 'Barracks'),
    'bsmith': (0x4a77, 'Blacksmith'),
    'bbombard': (0x4b04, 'Bombard Tower'),
    'bcastle': (0x4a7a, 'Castle'),
    'bdock': (0x4a7b, 'Dock'),
    'bfarm': (0x4b00, 'Farm'),
    'btrap': (0x4b02, 'Fish Trap'),
    'bgate': (0x4b40, 'Gate'),
    'bhouse': (0x4b0d, 'House'),
    'blumber': (0x4b53, 'Lumber Camp'),
    'bmarket': (0x4b25, 'Market'),
    'bmill': (0x4b24, 'Mill'),
    'bmining': (0x4b58, 'Mining Camp'),
    'bmonastery': (0x4a79, 'Monastery'),
    'bnext': (0x4b2b, 'More Buildings'),
    'boutpost': (0x4b03, 'Outpost'),
    'bpalisade': (0x4b0a, 'Palisade Wall'),
    'bsiege': (0x4b05, 'Siege Workshop'),
    'bstable': (0x4b06, 'Stable'),
    'bwall': (0x4b0b, 'Stone Wall'),
    'btower': (0x4b01, 'Tower'),
    'btc': (0x4b26, 'Town Center'),
    'buniversity': (0x4b08, 'University'),
    'bwonder': (0x4b09, 'Wonder'),
    'work': (0x4b7c, 'Go Back to Work'),
    'bell': (0x4b77, 'Ring Town Bell'),
    'vill': (0x4a6e, 'Villager'),
    'longboat': (0x4b78, 'Longboat'),
    'gcannon': (0x4a6f, 'Cannon Galleon'),
    'demoship': (0x4b50, 'Demolition Ship, Heavy Demolition Ship'),
    'fireship': (0x4b4f, 'Fire Ship, Fast Fire Ship'),
    'fish': (0x4a65, 'Fishing Ship'),
    'galley': (0x4a73, 'Galley, War Galley, Galleon'),
    'cog': (0x4a64, 'Trade Cog'),
    'transport': (0x4b54, 'Transport'),
    'eagle': (0x4a7e, 'Eagle Warrior, Elite Eagle Warrior'),
    'sword': (0x4a5b, 'Milita, Man-at-Arms, etc. (swordsmen)'),
    'spear': (0x4a5a, 'Spearman, Pikeman, Halberdier'),
    'archer': (0x4a5e, 'Archer, Crossbowman, Arbalest (archers)'),
    'cavarcher': (0x4a60, 'Cavarly Archer, Heavy Cavalry Archer'),
    'hcannon': (0x4a61, 'Hand Cannoneer, Slinger'),
    'skirm': (0x4a63, 'Skirmister, Elite Skirmisher'),
    'camel': (0x4a57, 'Camel, Heavy Camel'),
    'knight': (0x4a56, 'Knight, Cavalier, Paladin (knights)'),
    'scout': (0x4a74, 'Scout Cavalry, Light Cavalry, Hussar'),
    'ram': (0x4a70, 'Battering Ram, Capped Ram, Siege Ram'),
    'bcannon': (0x4a67, 'Bombard Cannon'),
    'mangonel': (0x4b55, 'Mangonel, Onager, Siege Onager'),
    'scorpion': (0x4a69, 'Scorpion, Heavy Scorpion'),
    'monk': (0x4a6b, 'Monk'),
    'cart': (0x4b56, 'Trade Cart'),
    'agg': (0x4b73, 'Aggressive'),
    'box': (0x4b67, 'Box'),
    'def': (0x4b74, 'Defensive'),
    'flank': (0x4b6a, 'Flank'),
    'follow': (0x4b72, 'Follow'),
    'guard': (0x4b71, 'Guard'),
    'line': (0x4b68, 'Line'),
    'noattack': (0x4b76, 'No Attack'),
    'patrol': (0x4b70, 'Patrol'),
    'stag': (0x4b69, 'Staggered'),
    'stand': (0x4b75, 'Stand Ground'),
    'treb': (0x4b79, 'Build Trebuchet'),
    'uu': (0x4b7a, 'Build Unique Unit'),

    # added in Conquerors
    'colors': (0x4b7f, 'Toggle Friend or Foe Colors'),
    'chapter': (0x4b80, 'Save Chapter'),
    'back': (0x4b7e, 'Return to Previous View'),
    'turtle': (0x4a80, 'Turtle Ship, Elite Turtle Ship'),
    'seed': (0x4a82, 'Reseed Farm'),
    'mission': (0x4a7f, 'Missionary'),
    'petard': (0x4a7d, 'Petard'),
    'huskarl': (0x4a81, 'Condottiero (Huskarl in HD)'),  # This was repurposed by DE, apparently

    # added in HD
    'elephant': (0x4a59, 'Battle Elephant, Elite Battle Elephant'),
    'cgroup1': (0x4b2c, 'Create Group #1'),
    'cgroup2': (0x4b2d, 'Create Group #2'),
    'cgroup3': (0x4b2e, 'Create Group #3'),
    'cgroup4': (0x4b2f, 'Create Group #4'),
    'cgroup5': (0x4b30, 'Create Group #5'),
    'cgroup6': (0x4b31, 'Create Group #6'),
    'cgroup7': (0x4b32, 'Create Group #7'),
    'cgroup8': (0x4b33, 'Create Group #8'),
    'cgroup9': (0x4b34, 'Create Group #9'),
    'cgroup0': (0x2c32d, 'Create Group #10'),
    'cgroup11': (0x2c32e, 'Create Group #11'),
    'cgroup12': (0x2c32f, 'Create Group #12'),
    'cgroup13': (0x2c330, 'Create Group #13'),
    'cgroup14': (0x2c331, 'Create Group #14'),
    'cgroup15': (0x2c332, 'Create Group #15'),
    'cgroup16': (0x2c333, 'Create Group #16'),
    'cgroup17': (0x2c334, 'Create Group #17'),
    'cgroup18': (0x2c335, 'Create Group #18'),
    'cgroup19': (0x2c336, 'Create Group #19'),
    'cgroup20': (0x2c337, 'Create Group #20'),
    'sgroup1': (0x4b36, 'Select Group #1'),
    'sgroup2': (0x4b37, 'Select Group #2'),
    'sgroup3': (0x4b38, 'Select Group #3'),
    'sgroup4': (0x4b39, 'Select Group #4'),
    'sgroup5': (0x4b3a, 'Select Group #5'),
    'sgroup6': (0x4b3b, 'Select Group #6'),
    'sgroup7': (0x4b3c, 'Select Group #7'),
    'sgroup8': (0x4b3d, 'Select Group #8'),
    'sgroup9': (0x4b3e, 'Select Group #9'),
    'sgroup0': (0x2c338, 'Select Group #10'),
    'sgroup11': (0x2c339, 'Select Group #11'),
    'sgroup12': (0x2c33a, 'Select Group #12'),
    'sgroup13': (0x2c33b, 'Select Group #13'),
    'sgroup14': (0x2c33c, 'Select Group #14'),
    'sgroup15': (0x2c33d, 'Select Group #15'),
    'sgroup16': (0x2c33e, 'Select Group #16'),
    'sgroup17': (0x2c33f, 'Select Group #17'),
    'sgroup18': (0x2c340, 'Select Group #18'),
    'sgroup19': (0x2c341, 'Select Group #19'),
    'sgroup20': (0x2c342, 'Select Group #20'),
    'attack': (0x30d48, 'Attack Move'),
    'bpgate': (0x4b0c, 'Palisade Gate'),
    'bfeitoria': (0x4a83, 'Feitoria'),
    'genitour': (0x4a58, 'Genitour'),
    'siegetower': (0x4a68, 'Siege Tower'),
    'caravel': (0x4a6d, 'Unique Warships'),

    # added in DE
    'tarson': (0x4c00, 'Tech: Arson'),
    'tus': (0x4c01, 'Tech: Elite Unique Ship'),
    'tarcher': (0x4c02, 'Tech: Crossbowman, Arbalester'),
    'tskirm': (0x4c03, 'Tech: Elite, Imperial Skirmisher'),
    'tcavarcher': (0x4c04, 'Tech: Heavy Cavalry Archer'),
    'tthumb': (0x4c05, 'Tech: Thumb Ring'),
    'tparthian': (0x4c06, 'Tech: Parthian Tactics'),
    'tgenitour': (0x4c07, 'Tech: Elite Genitour'),
    'tscout': (0x4c08, 'Tech: Light Cavalry, Hussar'),
    'tknight': (0x4c09, 'Tech: Cavalier, Paladin'),
    'tcamel': (0x4c0a, 'Tech: Heavy, Imperial Camel Rider'),
    'telephant': (0x4c0b, 'Tech: Battle Elephant, Steppe Lancer'),
    'tbloodlines': (0x4c0c, 'Tech: Bloodlines'),
    'thusbandry': (0x4c0d, 'Tech: Husbandry'),
    'tmeleeatt': (0x4c0e, 'Tech: Melee Attack Upgrades'),
    'tinfarm': (0x4c0f, 'Tech: Infantry Armor Upgrades'),
    'tcavarm': (0x4c10, 'Tech: Cavalry Armor Upgrades'),
    'tpierceatt': (0x4c11, 'Tech: Arrow Attack Upgrades'),
    'tpiercearm': (0x4c12, 'Tech: Archer Armor Upgrades'),
    'tram': (0x4c13, 'Tech: Capped, Siege Ram'),
    'tmangonel': (0x4c14, 'Tech: (Siege) Onager'),
    'tscorpion': (0x4c15, 'Tech: Heavy Scorpion'),
    'tredemption': (0x4c16, 'Tech: Redemption'),
    'tatonement': (0x4c17, 'Tech: Atonement'),
    'tfervor': (0x4c18, 'Tech: Fervor'),
    'tsanctity': (0x4c19, 'Tech: Sanctity'),
    'tfaith': (0x4c1a, 'Tech: Faith'),
    'tillumination': (0x4c1b, 'Tech: Illumination'),
    'tblock': (0x4c1c, 'Tech: Block Printing'),
    'theresy': (0x4c1d, 'Tech: Heresy'),
    'ttheocracy': (0x4c1e, 'Tech: Theocracy'),
    'therbal': (0x4c1f, 'Tech: Herbal Medicine'),
    'tmasonry': (0x4c20, 'Tech: Masonry, Architecture'),
    'ttreadmill': (0x4c21, 'Tech: Treadmill Crane'),
    'theated': (0x4c22, 'Tech: Heated Shot'),
    'tballistics': (0x4c23, 'Tech: Ballistics'),
    'tchemistry': (0x4c24, 'Tech: Chemistry'),
    'tengineers': (0x4c25, 'Tech: Siege Engineers'),
    'tarrowslits': (0x4c26, 'Tech: Arrowslits'),
    'tmurder': (0x4c27, 'Tech: Murder Holes'),
    'ttower': (0x4c28, 'Tech: Tower Upgrades'),
    'twall': (0x4c29, 'Tech: Fortified Wall'),
    'tbombard': (0x4c2a, 'Tech: Bombard Tower'),
    'smilitaryb': (0x4a3b, 'Select all Military Buildings'),
    'replayfaster': (0x4e3f, 'Replay Speed Up'),
    'replayslower': (0x4e40, 'Replay Speed Down'),
    'speedslow': (0x4e41, 'Set Speed to Slow'),
    'speeddef': (0x4e42, 'Set Speed to Default'),
    'speedfast': (0x4e43, 'Set Speed to Fast'),
    'speedxfast': (0x4e44, 'Set Speed to Extra Fast'),
    'sdock': (0x4a45, 'Select all Docks'),
    'srax': (0x4a46, 'Select all Barracks'),
    'srange': (0x4a47, 'Select all Archery Ranges'),
    'sstable': (0x4a48, 'Select all Stables'),
    'ssiege': (0x4a49, 'Select all Siege Workshops'),
    'scastle': (0x4a4a, 'Select all Castles'),
    'skrepost': (0x4a4b, 'Select all Kreposts'),
    'smonastery': (0x4a4c, 'Select all Monasteries'),
    'stc': (0x4a4d, 'Select all Town Centers'),
    'deleteall': (0x4a5c, 'Delete All Selected Units'),
    'eventback': (0x4a71, 'Review Event Messages Backward'),
    'eventforward': (0x4a72, 'Review Event Messages Forward'),
    'sland': (0x4a84, 'Select all Land Military Units'),
    'sidlev': (0x4a85, 'Select all Idle Villagers'),
    'slandvis': (0x4a86, 'Select all Visible Land Military Units'),
    'sidlet': (0x4a87, 'Select all Idle Trade Carts'),
    'tuu': (0x4a88, 'Tech: Elite Unique Unit'),
    'tuctech': (0x4a89, 'Tech: Unique Castle Technology'),
    'tuitech': (0x4a8a, 'Tech: Unique Imperial Technology'),
    'thoardings': (0x4a8b, 'Tech: Hoardings'),
    'tsappers': (0x4a8c, 'Tech: Sappers'),
    'tconscription': (0x4a8d, 'Tech: Conscription'),
    'tspies': (0x4a8e, 'Tech: Spies/Treason'),
    'zoomin': (0x4a8f, 'Zoom In'),
    'zoomout': (0x4a90, 'Zoom Out'),
    'zoomin2': (0x4a91, 'Zoom In'),
    'zoomout2': (0x4a92, 'Zoom Out'),
    'grid': (0x4a93, 'Toggle Visual Grid'),
    'ungroup': (0x4a9b, 'Ungroup Control Group'),
    'autofarm': (0x4a9c, 'Toggle Automatic Farm Reseeding'),
    'autotrap': (0x4a9d, 'Toggle Automatic Fish Trap Rebuilding'),
    'sellf': (0x4a9e, 'Sell 100 Food'),
    'sellw': (0x4a9f, 'Sell 100 Wood'),
    'sells': (0x4aa0, 'Sell 100 Stone'),
    'buyf': (0x4aa7, 'Buy 100 Food'),
    'buyw': (0x4aa8, 'Buy 100 Wood'),
    'buys': (0x4aa9, 'Buy 100 Stone'),
    'zoomreset': (0x4ab0, 'Reset Zoom'),
    'unsetgather': (0x4ab1, 'Remove Gather Point'),
    'gatelock': (0x4ab2, 'Lock/Unlock Gate'),
    'rtrap': (0x4ab3, 'Rebuild Fish Trap'),
    'tarkan': (0x4ab4, 'Tarkan'),
    'huskarl2': (0x4ab5, 'Huskarl'),
    'sling': (0x4ab6, 'Slinger'),
    'lancer': (0x4ab7, 'Steppe Lancer'),
    'dragscroll': (0x4ab8, 'Click-Drag Scroll'),
    'health': (0x4ab9, 'Toggle Health Bar'),
    'ungarrison': (0x4ef0, 'Ungarrison'),
    'cancel': (0x4b28, 'Cancel Build'),
    'scgroup1': (0x2c343, 'Select & Center Group #1'),
    'scgroup2': (0x2c344, 'Select & Center Group #2'),
    'scgroup3': (0x2c345, 'Select & Center Group #3'),
    'scgroup4': (0x2c346, 'Select & Center Group #4'),
    'scgroup5': (0x2c347, 'Select & Center Group #5'),
    'scgroup6': (0x2c348, 'Select & Center Group #6'),
    'scgroup7': (0x2c349, 'Select & Center Group #7'),
    'scgroup8': (0x2c34a, 'Select & Center Group #8'),
    'scgroup9': (0x2c34b, 'Select & Center Group #9'),
    'scgroup10': (0x2c34c, 'Select & Center Group #10'),
    'scgroup11': (0x2c34d, 'Select & Center Group #11'),
    'scgroup12': (0x2c34e, 'Select & Center Group #12'),
    'scgroup13': (0x2c34f, 'Select & Center Group #13'),
    'scgroup14': (0x2c350, 'Select & Center Group #14'),
    'scgroup15': (0x2c351, 'Select & Center Group #15'),
    'scgroup16': (0x2c352, 'Select & Center Group #16'),
    'scgroup17': (0x2c353, 'Select & Center Group #17'),
    'scgroup18': (0x2c354, 'Select & Center Group #18'),
    'scgroup19': (0x2c355, 'Select & Center Group #19'),
    'scgroup20': (0x2c356, 'Select & Center Group #20'),
    'agroup1': (0x2c357, 'Append Group #1'),
    'agroup2': (0x2c358, 'Append Group #2'),
    'agroup3': (0x2c359, 'Append Group #3'),
    'agroup4': (0x2c35a, 'Append Group #4'),
    'agroup5': (0x2c35b, 'Append Group #5'),
    'agroup6': (0x2c35c, 'Append Group #6'),
    'agroup7': (0x2c35d, 'Append Group #7'),
    'agroup8': (0x2c35e, 'Append Group #8'),
    'agroup9': (0x2c35f, 'Append Group #9'),
    'agroup10': (0x2c360, 'Append Group #10'),
    'agroup11': (0x2c361, 'Append Group #11'),
    'agroup12': (0x2c362, 'Append Group #12'),
    'agroup13': (0x2c363, 'Append Group #13'),
    'agroup14': (0x2c364, 'Append Group #14'),
    'agroup15': (0x2c365, 'Append Group #15'),
    'agroup16': (0x2c366, 'Append Group #16'),
    'agroup17': (0x2c367, 'Append Group #17'),
    'agroup18': (0x2c368, 'Append Group #18'),
    'agroup19': (0x2c369, 'Append Group #19'),
    'agroup20': (0x2c36a, 'Append Group #20'),
    'menu': (0x4b63, 'Menu'),
    'tooltips': (0x49579, 'Toggle Extended Tooltips'),
    'bkrepost': (0x4b81, 'Krepost'),
    'krepost': (0x4b82, 'Go to Krepost'),
    'gateclock': (0x4b83, 'Rotate Gate Clockwise'),
    'gatecounterclock': (0x4b84, 'Rotate Gate Counterclockwise'),
    'tloom': (0x4b85, 'Tech: Loom'),
    'twheel': (0x4b86, 'Tech: Wheelbarrow, Hand Cart'),
    'tlos': (0x4b87, 'Tech: Town Watch, Town Guard'),
    'tage': (0x4b88, 'Tech: Age Up'),
    'tfarm': (0x4b89, 'Tech: Farm Upgrades'),
    'tgold': (0x4b8a, 'Tech: Gold Upgrades'),
    'tstone': (0x4b8b, 'Tech: Stone Upgrades'),
    'twood': (0x4b8c, 'Tech: Wood Upgrades'),
    'tfish': (0x4b8d, 'Tech: Gillnets'),
    'ttransport': (0x4b8e, 'Tech: Careening, Dry Dock'),
    'tship': (0x4b8f, 'Tech: Shipwright'),
    'tgalley': (0x4b90, 'Tech: War Galley, Galleon'),
    'tdemoship': (0x4b91, 'Tech: Heavy Demolition Ship'),
    'tfireship': (0x4b92, 'Tech: Fast Fire Ship'),
    'tgcannon': (0x4b93, 'Tech: (Elite) Cannon Galleon'),
    'tcart': (0x4b94, 'Tech: Caravan'),
    'tcoin': (0x4b95, 'Tech: Coinage, Banking'),
    'w0': (0x4e45, 'Watch Gaia'),
    'w1': (0x4e46, 'Watch Player One'),
    'w2': (0x4e47, 'Watch Player Two'),
    'w3': (0x4e48, 'Watch Player Three'),
    'w4': (0x4e49, 'Watch Player Four'),
    'w5': (0x4e4a, 'Watch Player Five'),
    'w6': (0x4e4b, 'Watch Player Six'),
    'w7': (0x4e4c, 'Watch Player Seven'),
    'w8': (0x4e4d, 'Watch Player Eight'),
    'options': (0x4b51, 'Display Options Screen'),
    'tguilds': (0x4bfa, 'Tech: Guilds'),
    'tsword': (0x4bfb, 'Tech: Swordsmen Upgrades'),
    'tspear': (0x4bfc, 'Tech: Pikeman, Halberdier'),
    'teagle': (0x4bfd, 'Tech: (Elite) Eagle Warrior'),
    'tsupplies': (0x4bfe, 'Tech: Supplies'),
    'tsquires': (0x4bff, 'Tech: Squires'),

    #added later in de
    'kipchak' : (0x1c90, 'Elite Kipchak (Mercenary)'),

}

hk_groups = [

    ('Menus', [
        'object',
        'tech',
        'chatmenu',
        'diplomacy',
        'menu',
        'options',
    ]),
    ('Settings', [
        'colors',
        'stats',
        'time',
        'emap',
        'cmap',
        'nmap',
        'slow',
        'fast',
        'grid',
        'health',
        'tooltips',
    ]),
    ('Game Commands', [
        'flare',
        'pause',
        'save',
        'chapter'
    ]),
    ('Chat', [
        'chat',
        'chatback',
        'chatfor',
        'eventback',
        'eventforward',
    ]),
    ('Camera', [
        'dragscroll',
        'down',
        'left',
        'right',
        'up',
        'zoomin',
        'zoomout',
        'zoomin2',
        'zoomout2',
        'zoomreset',
        'back',
    ]),
    ('Spectator/Replay Commands', [
        'replayslower',
        'replayfaster',
        'speeddef',
        'speedxfast',
        'speedfast',
        'speedslow',
        'w0',
        'w1',
        'w2',
        'w3',
        'w4',
        'w5',
        'w6',
        'w7',
        'w8',
    ]),

    ('Control Groups', [
        'cgroup1',
        'cgroup2',
        'cgroup3',
        'cgroup4',
        'cgroup5',
        'cgroup6',
        'cgroup7',
        'cgroup8',
        'cgroup9',
        'cgroup0',
        'cgroup11',
        'cgroup12',
        'cgroup13',
        'cgroup14',
        'cgroup15',
        'cgroup16',
        'cgroup17',
        'cgroup18',
        'cgroup19',
        'cgroup20',
        'sgroup1',
        'sgroup2',
        'sgroup3',
        'sgroup4',
        'sgroup5',
        'sgroup6',
        'sgroup7',
        'sgroup8',
        'sgroup9',
        'sgroup0',
        'sgroup11',
        'sgroup12',
        'sgroup13',
        'sgroup14',
        'sgroup15',
        'sgroup16',
        'sgroup17',
        'sgroup18',
        'sgroup19',
        'sgroup20',
        'scgroup1',
        'scgroup2',
        'scgroup3',
        'scgroup4',
        'scgroup5',
        'scgroup6',
        'scgroup7',
        'scgroup8',
        'scgroup9',
        'scgroup10',
        'scgroup11',
        'scgroup12',
        'scgroup13',
        'scgroup14',
        'scgroup15',
        'scgroup16',
        'scgroup17',
        'scgroup18',
        'scgroup19',
        'scgroup20',
        'agroup1',
        'agroup2',
        'agroup3',
        'agroup4',
        'agroup5',
        'agroup6',
        'agroup7',
        'agroup8',
        'agroup9',
        'agroup10',
        'agroup11',
        'agroup12',
        'agroup13',
        'agroup14',
        'agroup15',
        'agroup16',
        'agroup17',
        'agroup18',
        'agroup19',
        'agroup20',
        'ungroup',
    ]),
    ('Go-To Commands', [
        'mill',
        'mining',
        'lumber',
        'dock',
        'smith',
        'market',
        'monastery',
        'university',
        'tc',
        'tc2',
        'rax',
        'range',
        'stable',
        'siege',
        'castle',
        'krepost',
        'idlem',
        'idlem2',
        'idlev',
        'idlev2',
        'selected',
        'last',
        'last2',
    ]),
    ('Select Commands', [
        'smilitaryb',
        'sdock',
        'srax',
        'srange',
        'sstable',
        'ssiege',
        'scastle',
        'skrepost',
        'smonastery',
        'stc',
        'sland',
        'sidlev',
        'slandvis',
        'sidlet',
    ]),
    ('All Units', [
        'delete',
        'deleteall',
        'garrison',
        'stop'
    ]),
    ('Military Units', [
        'attack',
        'patrol',
        'guard',
        'follow',
        'agg',
        'def',
        'stand',
        'noattack',
        'line',
        'box',
        'stag',
        'flank',
    ]),
    ('Siege Units', [
        'unpack',
        'pack',
        'ground',  # onager is different spot
    ]),
    ('Monks', [
        'convert',
        'heal'
    ]),
    ('Villagers', [
        'build',
        'mbuild',
        'repair',
        'cancel',
    ]),
    ('Buildings/Transports', [
        'setgather',
        'unsetgather',
        'work',
        'unload',  # transport is different spot
        'gatelock',
        'ungarrison',
    ]), ('Economic Build Menu', [
        'bhouse',
        'bmill',
        'bmining',
        'blumber',
        'bdock',
        'bfarm',
        'bsmith',
        'bmarket',
        'bmonastery',
        'buniversity',
        'btc',
        'bwonder',
        'bfeitoria',
        'bnext'
    ]), ('Military Build Menu', [
        'brax',
        'brange',
        'bstable',
        'bsiege',
        'boutpost',
        'bpalisade',
        'bwall',
        'btower',
        'bbombard',
        'bgate',
        'bpgate',
        'gateclock',
        'gatecounterclock',
        'bcastle',
        'bkrepost',
    ]),
    ('Fishing Ship Build', [
        'btrap',
        'rtrap',
        'autotrap',
    ]),
    ('Town Center', [
        'vill',
        'bell',
        'tloom',
        'twheel',
        'tlos',
        'tage',
    ]),
    ('Dock', [
        'fish',
        'transport',
        'cog',
        'galley',
        'demoship',
        'fireship',
        'gcannon',
        'caravel',
        'longboat',
        'turtle',
        'tfish',
        'ttransport',
        'tgalley',
        'tdemoship',
        'tfireship',
        'tgcannon',
        'tship',
        'tus',
    ]),
    ('Barracks', [
        'sword',
        'spear',
        'huskarl',
        'huskarl2',
        'eagle',
        'tsword',
        'tspear',
        'teagle',
        'tsupplies',
        'tsquires',
        'tarson',
    ]),
    ('Archery Range', [
        'archer',
        'skirm',
        'cavarcher',
        'hcannon',
        'genitour',
        'sling',
        'tarcher',
        'tskirm',
        'tcavarcher',
        'tgenitour',
        'tthumb',
        'tparthian',
    ]),
    ('Stable', [
        'scout',
        'knight',
        'camel',
        'elephant',
        'tarkan',
        'lancer',
        'tscout',
        'tknight',
        'tcamel',
        'telephant',
        'tbloodlines',
        'thusbandry',
    ]),
    ('Siege Workshop', [
        'ram',
        'mangonel',
        'scorpion',
        'bcannon',
        'siegetower',
        'tram',
        'tmangonel',
        'tscorpion',
    ]),
    ('Monastery', [
        'monk',
        'mission',
        'tredemption',
        'tatonement',
        'tfervor',
        'tsanctity',
        'tfaith',
        'tillumination',
        'tblock',
        'theresy',
        'ttheocracy',
        'therbal',
    ]),
    ('Market', [
        'cart',
        'tcart',
        'tcoin',
        'tguilds',
        'sellf',
        'sellw',
        'sells',
        'buyf',
        'buyw',
        'buys',
    ]),
    ('Castle', [
        'uu',
        'treb',
        'petard',
        'kipchak',
        'tuu',
        'tuitech',
        'tuctech',
        'thoardings',
        'tsappers',
        'tconscription',
        'tspies',
    ]),
    ('Mill', [
        'seed',
        'tfarm',
        'autofarm',
    ]),
    ('Mining Camp', [
        'tgold',
        'tstone',
    ]),
    ('Lumber Camp', [
        'twood',
    ]),
    ('Blacksmith', [
        'tmeleeatt',
        'tpierceatt',
        'tinfarm',
        'tcavarm',
        'tpiercearm',
    ]),
    ('University', [
        'tmasonry',
        'ttreadmill',
        'theated',
        'tballistics',
        'tchemistry',
        'tengineers',
        'tarrowslits',
        'tmurder',
        'ttower',
        'twall',
        'tbombard',
    ]),
]

if __name__ == '__main__':
    # check for duplicates in hk_groups
    assert sum(len(group[1]) for group in hk_groups) == len(hk_mapping)

    # check for presence of all keys in both
    assert set(hotkey for group in hk_groups for hotkey in group[1]) == set(hk_mapping.keys())
